name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set API key
      env:
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: echo client_secret=\"$CLIENT_SECRET\" > ./apikey.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Download schema
      run: |
        ./gradlew :app:downloadApolloSchema \
        --endpoint='https://api.github.com/graphql' \
        --schema=app/src/main/graphql/schema.json \
        --header='Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
